name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push with attestations
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ngfwautomation/ngfw-policy-as-code:${{ github.sha }}
            ngfwautomation/ngfw-policy-as-code:latest
          # ✅ add supply-chain attestations
          provenance: mode=max
          sbom: true
